In [ ]:
import numpy as np

# Array Creation

## 1-D Array without dtype

In [ ]:
a = np.array([2, 3, 4])

print(a, a.dtype, a.shape)

In [ ]:
b = b = np.array([1.2, 3.5, 5.1])

print(b, b.dtype, b.shape)

## 2-D Array

In [ ]:
c = np.array([(1.5, 2, 3), (4, 5, 6)])

print(c, c.dtype, c.shape)

## Specify the dtype

In [ ]:
c = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=np.float32)

print(c, c.dtype, c.shape)

## Special functions to Create Arrays

In [ ]:
# Create an array of all zeros
a = np.zeros((2,2))
print(a, a.dtype, a.shape)

In [ ]:
# Create an array of all ones
b = np.ones((1,2))
print(b, b.dtype, b.shape)

In [ ]:
# Create a constant array
c = np.full((2,2), 7)
print(c, c.dtype, c.shape)

In [ ]:
# Create a 2x2 identity matrix
d = np.eye(2)
print(d, d.dtype, d.shape)

## Array indexing

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

## Slicing

In [ ]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

In [ ]:
# A slice of an array is a view into the same data, so modifying it will modify the original array.
print(a[0, 1])   # Prints "2"

b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

## Integer indexing

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

## Mix integer indexing with Slice indexing

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a)

In [ ]:
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

## Boolean indexing

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [ ]:
bool_idx = (a > 2)

print(bool_idx)

In [ ]:
print(a[bool_idx])  # Prints "[3 4 5 6]"

In [ ]:
# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

# Array math

## Elementwise operations

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
print(x)

y = np.array([[5,6],[7,8]], dtype=np.float64)
print(y)

In [ ]:
# Elementwise sum
print(x + y)

print(np.add(x, y))

In [ ]:
# Elementwise difference
print(x - y)

print(np.subtract(x, y))

In [ ]:
# Elementwise product

print(x * y)

print(np.multiply(x, y))

In [ ]:
# Elementwise division

print(x / y)

print(np.divide(x, y))

In [ ]:
# Elementwise square root

print(np.sqrt(x))

## Matrix multiplication

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [ ]:
# Inner product of vectors
print(v.dot(w))

print(np.dot(v, w))

In [ ]:
# Matrix / vector product

print(x.dot(v))

print(np.dot(x, v))

In [ ]:
# Matrix / matrix product

print(x.dot(y))

print(np.dot(x, y))

## Transposing a matrix

In [ ]:
x = np.array([[1,2], [3,4]])
print(x)

print(x.T)

## Broadcasting

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y

y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

# This works; however when the matrix x is very large, computing an explicit loop in Python could be slow.

Note that adding the vector ```v``` to each row of the matrix ```x``` is equivalent to forming a matrix ```vv``` by stacking multiple copies of ```v``` vertically, then performing elementwise summation of ```x``` and ```vv```.

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Stack 4 copies of v on top of each other
vv = np.tile(v, (4, 1))
print(vv)

# Add x and vv elementwise
y = x + vv
print(y)

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of ```v```.

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Add v to each row of x using broadcasting
y = x + v

print(y)